### PR TITLE
Empty hist

### PR DESCRIPTION
**Pull request by ArjenHaag**
Ready for merging. Only thing I am not 100% sure about is the use of ee.Algorithms.If(). However, I could not think of a better way of handling this. @KMarkert, any ideas?

### CODE REVIEW

**Comment by ArjenHaag** [comment]
#11

**Comment by KMarkert** [comment]
Having a look at all of this, it looks good. The only way I can think of for users to avoid the EE server-side if statement is to have the default `no_data_thresh` equal `None`. This way users do not have to explicitly set it every time but have the option to fallback on for stability. Something like this:

```
def edge_otsu(..., no_data_thresh=None, ...):

    if no_data_thresh is not None:
        threshold = ee.Number(ee.Algorithms.If(...))
```

Let me know you thoughts, @ArjenHaag. If we want to make the change I can update the files.

**Comment by ArjenHaag** [comment]
Did you check the weird workaround I suggested in the issue itself (https://github.com/Servir-Mekong/hydra-floods/issues/11#issuecomment-737744438)?

**Comment by KMarkert** [comment]
Ahh, sorry! I haven't looked at that yet, only looked at the files changed in the PR.

I will do that ASAP.

**Pull request merged**
